### ISSUE TITLE
[EPIC] OpenM++ and model serving as a platform

### ISSUE THREAD

**Issue by chuckbelisle** [StatCan/openmpp#2]
Let's think about the big picture of how we want to serve Machine learning models and the OpenM++ features. There has also been discussions about converting existing models from ModGen to work with OpenM++. This issue will be the overarching place for information and tasks definition throughout the architecting and scoping of the project.

Note that for the time being it will live in the AAW github project, but assume that it will have its own in the very short term.

----------

It think it makes sense to reiterate some of the stuff that I put down in the performance agreement and separate that into smaller actionable tasks. Here are these components again:

- [x] StatCan/openmpp#1
- [x] StatCan/aaw#1835
- [ ] StatCan/aaw#1839
- [ ]  Setting up the existing OpenM++ browser based UI so that it runs as a web service on a public IP upon deployment.
- [ ]  A system for uploading and transpiling existing ModGen style microsimulation models into OpenM++ style models so that they can be run on the OpenM++ based deployment.
- [ ]  Enable running the parallelized version of OpenM++, which uses the MPI standard for parallel computing.
- [ ] I have some experience deploying and provisioning VMs directly, so that would be the approach that I'd like to use for the initial deployment. I can use my personal cloud account for initial prototyping to minimize organizational overhead.

From my reading of the OpenM++ wiki so far, the biggest functionality gap appears to be setting up OpenM++ as a service, and facilitating the uploading and transpiling of Modgen style models into OpenM++ style models. So in my opinion that would a priority in terms of providing a well-rounded service.

Also it might be good for me to engage in some learning tasks about kubernetes and aaw based deployments.
